"""Construit Article_resserre.docx et Supplementary_Data_resserre.docx à partir des versions de référence
(Article.docx md5 68caaeb7…, Supplementary_Data.docx md5 3b6f95e4…). Les passages retirés du texte principal
sont déplacés VERBATIM dans une nouvelle Note S2 du supplément ; l'ancienne Note S2 devient Note S3."""
import docx, re, copy, hashlib, json
M = 'docs/manuscrit/'  # lancer depuis la racine du dépôt (python3 avec python-docx)
from docx.shared import RGBColor, Pt
from docx.oxml.ns import qn

assert hashlib.md5(open(M + 'Article.docx', 'rb').read()).hexdigest() == '68caaeb7c55ec2716a7fa36010d898dd'
assert hashlib.md5(open(M + 'Supplementary_Data.docx', 'rb').read()).hexdigest() == '3b6f95e4f6ac72b5dc773f53c061d483'
A = docx.Document(M + 'Article.docx'); S = docx.Document(M + 'Supplementary_Data.docx')
P = list(A.paragraphs); SP = list(S.paragraphs)
ORIG = {i: p.text for i, p in enumerate(P)}
BLUE = RGBColor(0x1F, 0x4E, 0x79); GREY = RGBColor(0x88, 0x88, 0x88)
ITAL = ['Chondrostoma nasus', 'Parachondrostoma toxostoma', 'C. nasus', 'P. toxostoma', 'Neotoma', 'Takifugu',
        'Aspidoscelis', 'Kikihia', 'Escherichia coli', 'Salmonella enterica', 'Enterococcus faecalis',
        'Staphylococcus aureus']
IT_RE = re.compile('(' + '|'.join(re.escape(t) for t in ITAL) + ')')

def isgrey(r): return r.font.color is not None and r.font.color.type is not None and str(r.font.color.rgb) == '888888'
def nongrey(p): return ''.join(r.text for r in p.runs if not isgrey(r))

def add_runs(p, text, color=BLUE, before=None, bold_lead=None):
    pieces = []
    if bold_lead: pieces.append((bold_lead + ' ', False, True))
    for k, seg in enumerate(IT_RE.split(text)):
        if seg: pieces.append((seg, k % 2 == 1, False))
    for seg, it, bd in pieces:
        r = p.add_run(seg); r.italic = it or None; r.bold = bd or None
        if color is not None: r.font.color.rgb = color
        if before is not None: before.addprevious(r._r)

def set_text(p, text):
    """Remplace le texte non gris ; conserve les notes grises (placées après le nouveau texte)."""
    grey = [r for r in p.runs if isgrey(r)]
    for r in list(p.runs):
        if not isgrey(r): r._r.getparent().remove(r._r)
    add_runs(p, text, before=grey[0]._r if grey else None)

def set_grey(p, text):
    for r in list(p.runs):
        if isgrey(r): r._r.getparent().remove(r._r)
    r = p.add_run(text); r.italic = True; r.font.size = Pt(9); r.font.color.rgb = GREY

def delete(p): p._element.getparent().remove(p._element)

NEW = {}   # index -> nouveau texte (non gris)
DEL = []   # index supprimés du texte principal
MOVED = {} # index -> destination

# ----------------------------------------------------------------------------- Background
NEW[7] = ("Animals and their microbial communities form composite biological units in which microbial composition contributes to host performance and to tolerance of environmental constraints [1]. These associations are established largely by the sorting of environmental microbial pools according to host ecology and physiology — feeding behaviour and the immune pathways underlying tolerance of or resistance to microbes [2–4]. Environmental acquisition is particularly important in fish, which live in a medium favourable to bacterial growth, are continuously exposed to microbes at their epithelial barriers and are mostly oviparous, with limited maternal effects compared with mammals [5]; surveys of wild populations accordingly report a predominant environmental component of variation in bacterial composition [6–8]. Host genotype is nonetheless not without effect. In wild baboons followed over fourteen years, microbiome phenotypes were almost universally heritable, but with a typically low, context-dependent heritability that only large samples can quantify [9]; in stickleback, a host genetic influence on the gut microbiome became measurable once biological and technical components of variance had been decomposed [10]. Any effect of host ancestry on the fish microbiota is therefore expected to be small relative to the environmental one, and detecting it requires large samples and explicit control of the spatial and technical axes along which it could be mimicked.")
NEW[8] = ("Secondary contact zones make host ancestry a naturally occurring and naturally replicated variable. Introgressive hybridisation may disrupt co-adapted gene complexes and thereby alter close host–microbe interactions [11]; conversely, hybridisation is a source of genomic diversity and adaptive novelty [12, 13], which may extend to the microbiota through the acquisition of new microbial taxa. Three outcomes are usually contrasted: an intermediate microbiota, varying monotonically with ancestry; dominance, in which hybrids resemble one parental species; and a transgressive microbiota, lying outside the range of both parents. Camper et al. [14] formalised this comparison for host-associated microbiomes with four idealised models of taxon membership — Union, Intersection, Gain and Loss — whose relative weights sum to one; the Gain–Loss axis gives an operational definition of a transgressive microbiota that does not presuppose a cost to the host. The distinction matters: on an ecologically successful hybrid lizard, widespread transgressive segregation was correlated with a restructuring of niche, and the authors argue that the equation of transgression with dysbiosis rests disproportionately on hybrids of low adaptive value [15]. Following the framework's own statement of scope, we read the index as describing a pattern and not a process.")
NEW[9] = ("What is known of hybrid microbiota in fish comes almost entirely from controlled crosses: genotype corresponds closely to intestinal characteristics in reciprocal hybrids of bream and culter, whose parents have contrasting feeding habits [16]; host hybridisation outweighs cohabitation in intrageneric Takifugu hybrids [17]; reciprocal hybrids of koi and goldfish resemble one parent rather than the midpoint of the two [18]; and whitefish species pairs and their hybrids have been compared in natural and controlled environments [19] (reviewed in [20]). Studies of natural hybrid zones in other vertebrates do not converge. Host ancestry predominates in Neotoma woodrats, where habitat determines diet but genotype determines the gut microbiota [21], and in hybridising brown lemurs [22]; site soil properties rather than genetic ancestry explain the gut microbiota of baboons spanning a hybrid zone [23], and an apparent effect of admixture in wild house mice becomes weak once spatial autocorrelation is taken into account [24]. In hybridising chickadees moved to a common environment, the change of environment affected richness but not composition, while an effect of ancestry on composition was not supported [25] — an argument for reporting alpha and beta diversity separately. No study yet combines a natural hybrid zone in fish, host ancestry quantified by genotyping rather than assigned by cross class, and several tissue compartments characterised in the same individual.")
NEW[10] = ("The nase Chondrostoma nasus and the South-west European nase, or toxostome, Parachondrostoma toxostoma offer that combination. The toxostome is endemic to southern France, where it is declining and is a species of conservation concern; the nase, native to central Europe, entered the Rhône basin through navigable connections built across Europe during the last century [26], so that the two distributions have partially overlapped for about a hundred years. Hybridisation occurs in the patchily distributed sympatric areas of the basin, with an incidence unrelated to habitat characteristics [27–29] — the configuration of a mosaic hybrid zone [30]. Guivier et al. [31] characterised four tissue compartments of the two species in strict parapatry on a single river: the tissue compartment was the first factor of variation, externally and internally exposed tissues contrasted markedly, and species-specific taxa were asymmetric between compartments, numerous on the external tissues of the nase and in the intestine of the toxostome. They proposed that introgressive hybridisation might affect the microbiota differently depending on the tissue, a question their sixteen fish at two stations could not address. The present study addresses it on 180 fish sampled at nine stations over six watercourses of the Rhône drainage in two years, with host ancestry resolved by genotyping across 25 chromosomes and the same four compartments — caudal fin, gill, midgut and hindgut — characterised in each individual.")
NEW[11] = ("We ask whether the microbiota of individuals of mixed ancestry is intermediate between the two parental species, dominated by one of them or displaced outside their range, and whether the answer is the same in all four compartments. Three features of the design shape how the answer is reported. First, genotyping separates intermediate genomes from near-parental genomes introgressed on one or a few chromosomes, so that what counts as a hybrid is a decision: every contrast is run on intermediate hybrids alone and on all hybrids, both passes being declared in advance. Second, the comparison is reported both as a category contrast across stations and as the four-dimensional (4H) index of Camper et al. [14], whose settings are fixed a priori and whose sensitivity is reported. Third, genotypic category is entangled with station, the strongest correlate of composition, and with plate position, which followed field processing order; category effects are therefore bracketed between the two sequential orderings, with plate position as a covariate in a sensitivity analysis, and read as patterns co-varying with station and category rather than as effects of ancestry alone. Following Guivier et al. [31], we expect any hybrid signal to be most pronounced in the digestive compartments, where the two parental species diverge most.")

# ----------------------------------------------------------------------------- Methods
NEW[16] = ("We studied the host-associated bacterial microbiota of two interbreeding cyprinid fishes, the nase Chondrostoma nasus (code Cn) and the toxostome Parachondrostoma toxostoma (code Pt), and of their hybrids (code Hy), in their contact zone. Fish were sampled at nine stations of the Rhône drainage (rivers Durance, Suran, Buech, Beaume and Ardèche, and one canal fed by the Largue; south-eastern France) in 2014 and 2015, spanning a gradient of hybrid-zone context (allopatry, sympatry with hybridisation, asymmetric introgression). Two stations lie on the Suran, 25.4 km apart and separated by a barrier passable only downstream; they are treated as distinct because they carry different taxa.")
NEW[19] = ("Stations, coordinates, collection dates, genotypic composition and the numbers of individuals and libraries per station are given in Supplementary Table S1; coordinates and dates are field records supplied by the collecting team (see the note to Table S1). Individuals are counted per site code and year of sampling, which gives 180 individuals (156 if years are collapsed, because individual numbering restarts each year).")
DEL += [20]
NEW[21] = ("Species identity was resolved by genotyping rather than by morphology. Each individual was assigned, from a chromosome-level assignment across 25 chromosomes, to one of three categories — Cn (59 individuals), Hy (42) and Pt (79) — and not by thresholding a median hybrid index, because a substantial minority of hybrids carry an extreme median index and are identified by their inter-chromosome discordance. Genotypes were obtained from Q-scores on liver tissue for 175 individuals; of the remaining five, all parental, three were resolved from Q-score fits on midgut and caudal fin and two by an earlier, closely related method that left no Q-score record (Supplementary Table S2). Nine of the 49 individuals previously identified on morphology were reclassified. The Hy category comprises 20 intermediate genomes and 22 near-parental genomes, introgressed on a single chromosome in 17 cases, on two in four and on six in one. Every analysis of category is therefore run twice, both passes being declared in advance: pass 1 retains the 20 intermediate hybrids and excludes the 22 near-parental individuals, which are not reassigned to a parental category (158 individuals); pass 2 retains all 42 (180 individuals). Three stations carry all three categories — 74 individuals in pass 2 and 65 in pass 1, where Saint-Just-d'Ardèche retains a single hybrid — the subset in which the hybrid contrast can be tested within a station.")
NEW[26] = ("Bacterial DNA was extracted from each tissue with the Qiagen Food Mericon kit (Qiagen, Venlo, Netherlands), following a slightly modified protocol detailed in Guivier et al. [31]. A 251 bp fragment of the V4 region of the bacterial 16S rRNA gene was amplified with the dual-index method of Kozich et al. [32], with primers 515F GTGCCAGCMGCCGCGGTAA and 806R GGACTACHVGGGTWTCTAAT carrying an 8 bp index and Illumina adapters; amplification, purification and pooling followed Galan et al. [33]. Libraries were quantified with the Kapa quantification kit (Kapa Biosystems) and sequenced on an Illumina MiSeq with reagent kit v3 (2 × 251 bp paired-end reads, two 8 bp index reads) and a 10 % PhiX spike-in, on 10 July (durance1), 5 October (durance2) and 3 November 2017 (durance3).")
NEW[27] = ("The 768 samples were processed through two independent library preparations, each by the one-step dual-index PCR of Kozich et al. [32]. The first library was sequenced once (run durance1); the second, prepared from an independent PCR of the same samples, was sequenced twice on separate flow cells (durance2 and durance3). Because indices are incorporated during amplification, the two preparations carry different index assignments on the same plate layout (Supplementary Table S3). Each biological sample is thus represented three times in a nested structure — two library preparations, and two sequencing runs within the second — which separates the variability contributed by library preparation from that contributed by sequencing alone, neither being confounded with any biological factor; the structure was verified on the deposited data (Supplementary Note S1).")
DEL += [28]
NEW[30] = ("Negative controls comprised four extraction blanks, one per tissue, and eight no-template PCR controls, each sequenced in all three runs (36 negative-control samples). Two aliquots of the ZymoBIOMICS Microbial Community Standard (Zymo Research, cat. D6300), a defined mixture of eight bacterial taxa, served as positive controls (six mock samples across runs), and 25 empty wells that received no library were sequenced in all three runs (75 samples) to monitor index hopping. The biological samples, controls and empty wells deposited are listed in Supplementary Table S4.")
DEL += [31]; MOVED[30] = 'Note S2 (Controls)'
NEW[33] = ("Reads were processed with a version-controlled pipeline (cutadapt 5.0 [34]; R 4.5.3 with DADA2 1.38.0 [35]; SILVA v138.2 [36]; BLAST+ 2.13.0; FastQC and MultiQC), each run being processed separately through denoising. The 16S V4 primers co-amplify the host mitochondrial 12S rRNA gene (15–67% of reads per sample); because the host amplicon (~190 bp) is shorter than the bacterial one (~253 bp), host reads were removed by length with cutadapt. Amplicon sequence variants (ASVs) were inferred per run with DADA2 after quality filtering and truncation, with error models learned per run; the three sequence tables were merged keeping runs distinct, chimeras were removed (consensus method) and taxonomy was assigned against SILVA with the naïve Bayesian classifier and exact species matching. ASVs assigned to Eukaryota, Chloroplast or Mitochondria, or unassigned at the domain level, were removed. Parameters and their justification are given in Supplementary Note S2.")
DEL += [34, 35, 36, 37, 38, 39, 40, 41, 42, 43]
for i in (33, 35, 37, 39, 41, 43): MOVED[i] = 'Note S2'
NEW[45] = ("Processing yielded 44,349 ASVs across 2,295 of the 2,304 expected samples (nine were empty after filtering: eight controls and one biological sample present in the two other runs). ASV length peaked sharply at 251 bp, with no residual 12S.")
MOVED[45] = 'Note S2'
NEW[47] = ("The six mock samples (two aliquots × three runs) validated ASV inference: all recovered the eight expected species, the eight dominant ASVs matched the ZymoBIOMICS reference at 100 % identity over 251 bp, confidently matching reads (BLASTn, ≥99 % identity over ≥240 aligned bp) represented ~100 % of reads in every mock, and no spurious ASV exceeded 1 % (reference strain set and lot in Supplementary Note S2).")
DEL += [48]; MOVED[47] = MOVED[48] = 'Note S2'
NEW[51] = ("Contaminants were identified with decontam v1.30.0 [37] by the prevalence method against the 36 negative controls, batches being defined by sequencing run; DNA concentrations, required by the frequency method, were not available. The default threshold of 0.1 flagged 66 ASVs (0.15 % of ASVs) while retaining 99.76 % of reads, the flagged taxa being typical reagent contaminants; a threshold of 0.5 removed 1.89 points more reads, including ASVs carrying biological signal, and was rejected (Supplementary Note S2).")
MOVED[51] = 'Note S2'
NEW[53] = ("Index hopping was quantified on the 75 empty-well samples, in which any read represents leakage: they accumulated 41 reads out of 26.8 million (0.0002 %; median 0 reads per well, maximum 13), and no background subtraction was applied.")
NEW[55] = ("The ten ASVs matching the mock reference strains were used as exogenous tracers. Two nominal individuals, each a single caudal-fin sample dominated by mock ASVs (70 % and 99 % of reads) and placed in the wells and index series of the mock controls, were mislabelled mock wells and were excluded. Nine further individuals carried mock ASVs at 20–65 % in a single well-tissue combination, their other tissues being unaffected, consistent with well-level contamination (Supplementary Note S2). Mock ASVs were removed from all samples, and ASVs left with zero counts were discarded.")
MOVED[55] = 'Note S2'
NEW[59] = ("A de novo phylogeny of the ASVs was built with QIIME 2 [38] (MAFFT alignment [39], masking of highly variable positions, FastTree 2 [40], midpoint rooting), de novo alignment being appropriate for near-complete V4 amplicons; it supports UniFrac distances [41] and Faith's phylogenetic diversity [42].")
MOVED[59] = 'Note S2'
NEW[61] = ("Sequencing effort was equalised by rarefaction [43]. A depth of 3,000 reads was chosen on three criteria: richness plateaued below it in rarefaction curves; it retained 81.8 % of samples (1,784/2,180), against 72.6 % at 5,000 reads; and retention was balanced across sequencing runs (80.2–83.5 % per run), so that depth is not confounded with batch.")
NEW[62] = ("Rarefaction was repeated rather than drawn once [44], and metrics rather than count tables were averaged, since averaging tables would inflate observed richness above what 3,000 reads can support: alpha indices over 1,000 rarefactions, Bray–Curtis and Jaccard matrices over 400, and unweighted UniFrac, weighted normalized UniFrac and Faith's phylogenetic diversity over 400 draws run as two independent chains. Monte-Carlo error, measured between independent chains, was negligible relative to the technical and biological dissimilarities (Supplementary Table S5; details in Supplementary Note S2).")
DEL += [63, 64, 65]
for i in (61, 62, 63, 64, 65, 66): MOVED[i] = 'Note S2'
NEW[66] = ("Because the threshold also decides which samples enter, the two effects were separated. On the samples retained at 3,000 reads, matrices recomputed at 500 reads were nearly invariant for the abundance-weighted metrics (weighted UniFrac r = 0.9994, Bray-Curtis r = 0.9985) but not for the presence-based ones (Jaccard r = 0.9617, unweighted UniFrac r = 0.9373), observed richness falling by 42 %. Retention at 3,000 reads is not random with respect to category: in the caudal fin 50 % of intermediate hybrids passed the threshold against 86 % of P. toxostoma (pass 1), and 67 % of all 42 hybrids (pass 2), a gap of 36 and 20 points respectively. Claims resting on abundance-weighted metrics are therefore accompanied by a sensitivity analysis at 500 reads, where the caudal-fin gap falls to 3.8 points (pass 1) and 5.7 points (pass 2) and 2,067 samples are retained (1,825 in pass 1); claims resting on presence-based metrics are reported at 3,000 reads with the selection declared, the midgut gap (14.0 and 8.9 points) persisting at 500 reads in any case (Supplementary Table S6 and Figure S2).")
NEW[68] = ("Community composition was analysed by PERMANOVA [45] on the averaged dissimilarity matrices, stratified by tissue, a stratification imposed by the design: 168 of the 180 fish occupy the same plate column across all four tissues, so that plate position is not estimable in a pooled model carrying fish identity. Station, not site code, is the spatial unit, since two site codes each span two Suran stations that share no genotypic category; sequencing run is nested within library preparation (§8.8), and every analysis of category is run in the two passes of §1. Because genotypic category, station and plate position are mutually entangled (Results), each model is fitted in both sequential orderings and the interval between them is reported, the ordering that serves category first bounding it from above and the ordering that serves it last from below. Plate column is not entered in the principal models, but every model testing category is refitted with it as a covariate and reported as a sensitivity analysis. Permutations are constrained within station blocks where the question concerns a within-station contrast. Dispersion was tested with PERMDISP [46], since the transgressive hypothesis concerns the variability of hybrid microbiota and PERMANOVA is itself sensitive to heterogeneous dispersion; distances to group medians were corrected for small-sample bias (bias.adjust = TRUE [48]), hybrids being the smallest category in every stratum. Both analyses were run with vegan 2.7-5 [47]. Four dissimilarities — Bray–Curtis, Jaccard, unweighted and weighted UniFrac — and four alpha indices — observed richness, Shannon, inverse Simpson and Faith's phylogenetic diversity — are reported per tissue. Because resequencing one library recovers only 48 % of the ASVs present at 1–3 reads (Results), a result is stated as established only where at least one abundance-weighted and one presence-based metric support it, and is otherwise reported as metric-dependent with the supporting metrics named; the rule is applied metric by metric, since Bray–Curtis patterns with the two presence-based dissimilarities whereas weighted UniFrac stands apart. Running text quotes Shannon and Bray–Curtis, the remaining metrics being reported alongside.")
NEW[74] = ("Alpha diversity was summarised per individual and tissue as the mean over the three runs of the four rarefied indices, analysed on the log scale. First, external (caudal fin, gill) and internal (midgut, hindgut) compartments, and midgut and hindgut, were contrasted within individual by paired t-tests on log values, with Wilcoxon signed-rank tests alongside, and expressed as ratios of geometric means with 95 % confidence intervals. Second, the variance of log alpha diversity over the 1,784 rarefied samples was partitioned by a linear model with tissue, site-year, individual, library preparation and sequencing run, reporting sequential and marginal shares. Third, genotypic category was tested per tissue and pass by ordinary least squares, log(index) ~ station + category, with an F test of the category term and the contrasts hybrid − C. nasus, hybrid − P. toxostoma and hybrid − parental midpoint with 95 % confidence intervals; plate position was added as a covariate in a sensitivity model. Hybrids were classified as intermediate when their estimate lay between the two parental estimates and did not differ from their midpoint; as dominant when their interval included one parent and excluded the other; as transgressive when their estimate lay beyond the parental range with an interval excluding the nearer parent; and as undetermined when no criterion or more than one was met. This rule, and the controls of §8.12, were declared before computation.")
NEW[76] = ("The 4H index [14] was computed with the R package HybridMicrobiomes 0.1.1 [49] and phyloseq [50] on three host classes — C. nasus, hybrids and P. toxostoma — in each pass, tissue and sequencing run. Its parameters and reading rules were fixed in a document committed before any index was computed: core fraction ρ = 0.5 at genus rank, with sensitivity at ρ = 0.3 and 0.7 and at family rank, and no abundance threshold (ϑ = ε = 0); ρ ≥ 0.8 was excluded because the Intersection dimension vanishes there on the published natural hybrid system. Counts were aggregated to genus — 48.6 % of ASVs, carrying 64.1 % of reads, were assigned to a genus (family: 77.9 % and 90.6 %) — and unassigned ASVs were excluded. Samples carrying at least 1,000 genus-assigned reads (1,749 of the 1,784 rarefied samples) were rarefied to that depth at each of 500 bootstraps; on the published natural hybrid system the parental axis varies by at most 0.067 between 1,000 and 10,000 reads [14]. Each bootstrap drew without replacement the same number of hosts N from each class, N being one less than the smallest class of pass 1 in the stratum (9 in the caudal fin, 10–19 elsewhere), and the same N was applied to pass 2; pass 2 was also computed at its own N. The abundance-based version of the index, the pre-analysis of core fractions, the null plane and a null hybrid averaging one randomly drawn individual of each parental species were computed with the same settings. An axis — parental (Union + Intersection) or transgressive (Gain + Loss) — was called dominant when it exceeded 0.5 in all three runs, and robust when the same axis also dominated at ρ = 0.3, at ρ = 0.7, at family rank and in the abundance-based version; two compartments were called different when the 95 % bootstrap intervals of the transgressive axis were disjoint in all three runs. The PERMANOVA comparison of bootstrap sets offered by the package was not used, because its p-value decreases with the arbitrarily chosen number of bootstraps. Preferential retention of the taxa shared by both parents was inferred when more than 95 % of bootstraps lay on the Intersection side of the null plane in all three runs.")
NEW[81] = ("Raw sequence data have been deposited in the European Nucleotide Archive (ENA) under accession PRJEB124417: 768 samples and 2,304 sequencing runs (4,608 FASTQ files, 11.7 GB), with run titles encoding the nested replication structure of §8.8, sample metadata following the GSC MIxS host-associated checklist (ERC000013), and controls, mock aliquots and empty wells included and identified as such. Per-run accessions, file names and MD5 checksums are given in Supplementary Table S7.")
MOVED[81] = 'Note S2'
NEW[82] = ("ENA metadata were corrected after the initial deposit to field-record coordinates, exact collection dates and genotype-resolved host identities, without altering any accession, alias or sequence file (Supplementary Note S2); host subject identifiers are reused between years (Supplementary Note S3). Collection dates are given at day resolution for every station except Pertuis, where the two 2014 fishing campaigns are deposited as the interval 2014-07-07/2014-08-20.")
MOVED[82] = 'Note S2'
DEL += [83]

# ----------------------------------------------------------------------------- Results
NEW[91] = ("The two runs sharing a library were markedly more similar to each other (mean Bray–Curtis 0.118, Jaccard 0.445) than either was to the run from the independent library (0.248 and 0.720 respectively; 548 samples reaching 3,000 reads in all three runs, §8.8); the two library-crossing comparisons were statistically indistinguishable from each other (paired Wilcoxon, p = 0.48) and both differed from the within-library comparison (p < 10⁻⁸⁹). Recapture of rare ASVs (1–3 reads) showed the same pattern (0.48 within library vs 0.19 across): library preparation roughly doubles the technical dissimilarity contributed by sequencing alone, with a proportionally larger effect on presence–absence than on relative abundances. Sequencing run was accordingly modelled as nested within library preparation; because each sample is present in every batch, technical and biological factors are crossed rather than confounded, and no batch correction was applied.")
DEL += [92]
NEW[93] = ("Relative to the biological signal, this technical variation is negligible. With the technical terms entered first, library preparation explained 0.03 % of the Bray–Curtis variance over the 1,784 rarefied samples (R² = 0.0003, p = 0.63) and sequencing run within library 0.005 % (p = 1.00), against 9.2 % for tissue and 37.7 % for fish identity (both p = 0.002); library preparation cannot be tested marginally, being aliased with run label. Mean Bray–Curtis dissimilarity was 0.13 between two sequencing runs of one library and 0.25 across libraries, against 0.88 between different fish of the same tissue and 0.94 across tissues.")
NEW[96] = ("Three witnesses separate this effect from the biology it could be mistaken for. Within a single genotypic category, where a column effect cannot be a category effect, it persists but more weakly: among P. toxostoma alone in 17 of 24 strata in both passes (ratio 1.65), among C. nasus alone in 6 (pass 1) and 7 (pass 2) of 24 (ratio 1.63); hybrids alone are too few to be tested, and the only single-category station (Chavannes-sur-Suran, 19 P. toxostoma) is too small for a separate witness. In the symmetric ordering with category fitted first, column still contributes (21 and 22 of 24 strata). And plate row is significant in 7 and 6 of 24 strata and plate edge in none, making the effect specific to column, as expected of an effect tracking processing order rather than evaporation or thermal gradients. The mechanism of the column effect is not identified: extraction order, reagent-batch drift within a plate, cross-contamination between adjacent wells and the delay between capture and dissection are not separated by these data, and no negative control isolates any of them.")
NEW[103] = ("Fitted in both orderings without plate position, genotypic category accounted for a median of 1.7 % to 2.8 % of compositional variance across the 48 metric × tissue × run strata in pass 1 and 1.4 % to 3.0 % in pass 2, against a median of 19 % and 18 % for station fitted after category (range across strata 14–36 % in pass 1 and 14–35 % in pass 2) and of 20.9 % and 20.1 % for station fitted first (Fig. 3c; Supplementary Table S9). No tissue is detected by all four metrics in all three runs under both permutation schemes, in either pass, with or without plate position (Fig. 3a, b), so a global statement that hybrids differ is not supportable. One result is robust to every choice made here — both passes, with and without plate position, all three runs and both permutation schemes: the midgut on Jaccard (p ≤ 0.044). The caudal fin on weighted UniFrac is detected in all three runs and both schemes in pass 1 (p = 0.007–0.024), with or without plate position, and in no run in pass 2 (p = 0.073–0.235). Removing 22 randomly chosen individuals from the 158 that are not introgressed, twenty times, never restored the caudal signal in pass 2, which attributes this displacement to the definition of hybrids rather than to sample size. At 500 reads the caudal signal is partial in pass 1 (three runs sequentially, p = 0.022–0.049; one of three with station fixed by blocks) and absent in pass 2; restricted to the samples retained at 3,000 reads, the 500-read matrices give the same result as at 3,000 reads (all three runs, both station-blocked schemes, p = 0.010–0.026), so that the attenuation reflects dilution by the caudal-fin samples that pass the threshold only at 500 reads, not depth. As at 3,000 reads, none of twenty random removals of 22 non-introgressed individuals from pass 2 reproduced the pass-1 pattern at 500 reads. The hindgut is the weakest tissue in pass 1 (only Jaccard is significant, in one run of three with station fixed by blocks) but in pass 2 all four metrics detect it in all three runs with station fixed by blocks; the witness does not resolve whether this difference reflects sample size or the definition of hybrids. The principal and sensitivity models differ in 7 of the 16 metric × tissue cells in each pass, of which 5 (pass 1) and 3 (pass 2) move between robust detection (three runs, both schemes), partial detection and none. The separable sub-design detects category in 3 of 48 tests in pass 1 and 1 of 48 in pass 2 (with plate position), and Rosières, in pass 2, detects it in the gill on Jaccard and unweighted UniFrac in all three runs (p = 0.010–0.030).")
NEW[104] = ("Whether the loss of the caudal-fin signal between passes is produced by dilution of the hybrid–P. toxostoma contrast by the 19 near-parental hybrids of P. toxostoma background was tested (§8.12) and remains undetermined. Relabelling as hybrids 19 P. toxostoma and 3 C. nasus drawn from the stations of the near-parental individuals removed the pass-1 signal in 16 of 20 draws, so that such dilution is sufficient to produce the displacement; but the near-parental hybrids of P. toxostoma background differed neither from pure P. toxostoma (p = 0.28–0.60) nor from intermediate hybrids (p = 0.15–0.26; n = 25–26), so that dilution is not established.")
NEW[107] = ("Because PERMANOVA is sensitive to heterogeneous dispersion, this bears on the location results. With station fixed by blocks, dispersion in the caudal fin was homogeneous on all four metrics in pass 2 and in all but one test in pass 1 (weighted UniFrac, one run of three, p = 0.048, hybrids most dispersed), so that the caudal-fin location signal on weighted UniFrac in pass 1 is a difference in composition in two runs and cannot be separated from a dispersion difference in the third. The robust midgut signal on Jaccard was accompanied by homogeneous dispersion in pass 1 and in two runs of three in pass 2. By contrast, dispersion was heterogeneous in all three runs in the midgut on unweighted UniFrac in both passes and, in pass 2, in the midgut and hindgut on Bray–Curtis, P. toxostoma being the most dispersed category there; the location signals on those metrics in those compartments cannot be separated from a dispersion effect. Because betadisper accepts no covariate, the plate-position effect is not adjusted for, and a category whose samples are more spread across plate columns could carry inflated dispersion. Supplementary Table S10 and Figure S3.")

# ----------------------------------------------------------------------------- Discussion
NEW[112] = ("Across alpha diversity, community dispersion and the 4H index, the microbiota of hybrids between C. nasus and P. toxostoma showed no transgressive pattern. Where hybrids could be placed relative to their parents, they fell within the parental range: dominance of C. nasus in caudal-fin alpha diversity in pass 1, a parental, Intersection-dominated 4H index in the gill, and preferential retention of the core taxa shared by both parental species in every compartment. The departures detected in composition were small — genotypic category accounted for a median of 1.4–3.0 % of compositional variance against about a fifth for station — and confined to particular compartments, metrics and definitions of a hybrid. This places the system with natural hybrid zones in which the environmental component dominates [23, 24] rather than with those in which host ancestry does [21, 22], while keeping in view that a small genetic effect is the expected magnitude for a heritable but weakly heritable trait [9], detectable only once the spatial and technical axes have been separated [10].")
NEW[113] = ("The expectation derived from Guivier et al. [31], that a hybrid signal would be most pronounced in the digestive compartments, is partly supported. The only compositional result that withstood every analytical choice concerned the midgut, on a presence-based metric, and in pass 2 both digestive compartments were detected by all four metrics with station fixed by blocks. But the caudal fin carried, in pass 1, a signal on weighted UniFrac that no digestive compartment showed on that metric, the gill was the compartment in which the 4H index was robustly parental, and the 4H index distinguished no pair of compartments. Hybrid status therefore does not matter equally in all compartments, but which compartment carries a difference depends on the metric. Requiring both an abundance-weighted and a presence-based metric makes this dependence explicit rather than resolving it; it also accounts for the 4H index, a presence-based construct in its principal form, departing from its abundance-based version in every compartment but the gill.")
NEW[114] = ("How hybrids are defined mattered as much as which compartment is examined. The caudal-fin signal obtained with the 20 intermediate hybrids disappeared when the 22 near-parental individuals were added, and random removals of 22 non-introgressed fish never reproduced the displacement, which is therefore attributable to who is called a hybrid rather than to sample size; whether near-parental hybrids of P. toxostoma background dilute the contrast because their microbiota resembles that of P. toxostoma could not be established at the available sample size. In a mosaic hybrid zone [30] in which most introgressed individuals depart from a parental genome on a single chromosome, a hybrid class is a decision, and we suggest that studies of natural hybrid zones report their results under both definitions.")
NEW[115] = ("That hybrids were not more dispersed than their parents runs against the expectation that genomes combining parental elements in variable proportions carry more variable microbiota. The opposite tendency, hybrids less dispersed than both parents, was clear only in pass 2 with station fixed by blocks, absent within stations and carried mainly by Bray–Curtis, and should not be read as a general property of hybrids here. The analysis also illustrates a pitfall of unbalanced designs: without correction for group size, the distance to the group centre is underestimated in small groups, and because hybrids were the smallest category in every stratum, the uncorrected analysis yielded a strong and apparently replicated reduction of hybrid dispersion — 32 of 48 station-blocked tests in pass 1 and 45 of 68 within stations — that largely disappeared once corrected. Hybrid classes are small in most natural hybrid zones, and the correction should be applied by default in that setting [48].")
NEW[116] = ("The 4H index adds two points. First, in its abundance-based version — the form in which the framework's authors compared published systems [14] — the index placed every compartment on the parental axis (Gain + Loss = 0.22–0.35), as in the Neotoma woodrat system (0.12) and unlike the Aspidoscelis lizard and Kikihia cicada systems (0.71 and 0.64); since transgression has been associated with ecological success rather than with dysbiosis in a hybrid lizard [15], its absence here carries no implication for hybrid fitness either way. Second, as its authors found for a natural hybrid system, the index was sensitive to its settings: the choice between presence and abundance reversed the reading in three compartments of four, and in the caudal fin so did the number of hosts per class, from 9 to 26–27. A null hybrid built from parental individuals already sits close to the 0.5 boundary between the two axes, which makes that boundary a weak criterion for calling a hybrid microbiota transgressive. We therefore read the 4H index as a description of taxon membership conditional on its settings, not as an independent test of the intermediate, dominant and transgressive hypotheses.")
NEW[117] = ("Four limits bound these conclusions. Genotypic category is confounded with station, and the three stations carrying all three categories hold 65–74 individuals, so that category effects are estimated mostly between stations. Plate position affected composition and followed processing order in every campaign; its mechanism — extraction order, reagent drift within a plate, cross-contamination between adjacent wells or time spent in the holding tank — is not identified, and because C. nasus was generally processed first it could contribute to the dominance of C. nasus in caudal-fin alpha diversity, which was not tested. Rarefaction to 3,000 reads retained intermediate hybrids less often than P. toxostoma in the caudal fin, a selection that is declared but cannot be removed for presence-based metrics. And only 64 % of reads could be aggregated to genus for the 4H index, whose genus-level reading therefore rests on the better-assigned part of each community.")

# ----------------------------------------------------------------------------- Note S2 (verbatim moves)
def mv(i, subs=()):
    t = ORIG[i] if i not in GREYFREE else GREYFREE[i]
    for a, b in subs: 
        assert a in t, (i, a); t = t.replace(a, b)
    return t
GREYFREE = {i: nongrey(P[i]) for i in range(len(P))}
NOTE = [
 (None, "This note gives in full the parameters and controls summarised in Materials and Methods §4–§9 of the main text; the paragraphs are those of an earlier, longer version of the Methods, moved here unchanged except for cross-references. Reference numbers refer to the main-text reference list."),
 ("Library preparation and sequencing.", mv(26)),
 ("Replication structure.", mv(27, [("(Supplementary Data, Index assignment)", "(Table S3)")])),
 ("Controls.", mv(30)),
 ("Pipeline.", mv(33)),
 ("Quality control.", mv(35)),
 ("Removal of co-amplified host 12S rRNA.", mv(37)),
 ("ASV inference (DADA2, per run).", mv(39)),
 ("Table merging, chimera removal and taxonomy.", mv(41)),
 ("Non-target filtering.", mv(43)),
 ("Resulting dataset.", mv(45)),
 ("Mock community.", mv(47)),
 (None, mv(48)),
 ("Decontamination.", mv(51)),
 ("Index hopping.", mv(53)),
 ("Mock-derived sample-level artefacts.", mv(55)),
 ("Phylogenetic tree.", mv(59)),
 ("Choice of rarefaction depth.", mv(61)),
 ("Repeated rarefaction.", mv(62)),
 ("Monte-Carlo error.", mv(63, [("reported in Results", "reported in the main-text Results"), ("(Results)", "(main text, Results)"), ("Supplementary Table S5", "Table S5")])),
 (None, mv(64)),
 ("Phylogenetic metrics.", mv(65)),
 ("Depth and sample selection.", mv(66, [("Supplementary Table S6 and Figure S2.", "Table S6 and Figure S2.")])),
 ("ENA submission.", mv(81, [("described in §8.8", "described in Materials and Methods §8.8"), ("(§8.2)", "(Materials and Methods §8.2)"), ("Supplementary Table S7", "Table S7")])),
 ("ENA metadata corrections.", mv(82)),
 (None, mv(83, [("Supplementary Table S1", "Table S1")])),
]
json.dump({'NEW': NEW, 'DEL': DEL, 'MOVED': {str(k): v for k, v in MOVED.items()}, 'ORIG': ORIG}, open('results/verif_article/resserre_edits.json', 'w'), ensure_ascii=False)

# ----------------------------------------------------------------------------- application à l'article
for i, t in NEW.items(): set_text(P[i], t)
h = P[32]; assert h.text.startswith('5. Sequence processing'); 
for r in h.runs[1:]: r._r.getparent().remove(r._r)
h.runs[0].text = '5. Sequence processing'
# phrase retirée du §8.7 : signalée en note grise
r = P[68].add_run(" [Phrase retirée au resserrement du 2026-10-05 : « The choice of a differential-abundance method remains to be fixed. » Aucune analyse d'abondance différentielle n'est rapportée ; à trancher par JF.]")
r.italic = True; r.font.size = Pt(9); r.font.color.rgb = GREY
set_grey(P[104], " [Médianes de station : 19 % et 18 % lorsque la station est servie après la catégorie (étendue 14–36 % et 14–35 %), 20,9 % et 20,1 % lorsqu'elle est servie en premier. La formulation « not as a result of it » a disparu au resserrement du 2026-10-05.]")
# note grise d'en-tête
hdr = P[1].insert_paragraph_before('')
r = hdr.add_run("[Version resserrée du 2026-10-05. Les passages retirés des Methods sont déplacés sans modification dans la nouvelle note supplémentaire S2 de Supplementary_Data_resserre.docx ; l'ancienne note S2 devient la note S3. Comparaison paragraphe par paragraphe : docs/manuscrit/resserrement_2026-10-05_comparaison.docx. Article.docx reste la version de référence jusqu'à validation par JF.]")
r.italic = True; r.font.size = Pt(9); r.font.color.rgb = GREY
for i in sorted(set(DEL), reverse=True): delete(P[i])
A.save(M + 'Article_resserre.docx')

# ----------------------------------------------------------------------------- supplément
def fix(i, a, b):
    p = SP[i]; done = False
    for r in p.runs:
        if a in r.text: r.text = r.text.replace(a, b); done = True
    assert done, (i, a)
fix(19, "reported in §8.7 of the Materials", "reported in §3 and §8.8 of the Materials")
fix(28, "scales reported in §8.7", "scales reported in the main-text Results")
fix(41, "(§8.6, §8.8)", "(§8.7, §8.9)")
fix(54, "Note S2.", "Note S3.")
anchor = SP[21]  # paragraphe vide après la Note S1, avant la Table S4
newp = []
hp = anchor.insert_paragraph_before('', style=SP[18].style)
r = hp.add_run('Note S2. Sequence processing, quality control and repeated rarefaction'); r.font.color.rgb = BLUE
for lead, body in NOTE:
    q = anchor.insert_paragraph_before('', style=S.styles['Normal'])
    add_runs(q, body, bold_lead=lead)
S.save(M + 'Supplementary_Data_resserre.docx')
print('ok')
